### ISSUE TITLE
pet-training-timer.user.js - Does not account for Training Fortune Cookie bonus

### ISSUE THREAD

**Issue by Jutakl** [systematic-meerca/neopets-display-scripts#1]
The Neopets Pet Training Timer does not adjust timers based on the reductions which are randomly assigned after paying for a course when having the Neocash Training Fortune Cookie bonus active. This renders the script almost unusable for people who are using the Training Fortune Cookie, outside of serving as a quick link to the training school pages.

**Comment by Merleawe** [comment]
I'm having the same issue. It would be nice if it could be fixed.

**Comment by Merleawe** [comment]
Since the Author isn't here.... here is the fix (**Thank you Flutterz on discord!**)

let cookie = 0;
if (cell.innerHTML.includes("strikethrough"))cookie = 3;
if (cell.innerHTML.includes("strikethrough")){
totalTime = (
Number.parseInt(time[0+cookie]) * 60 * 60 * 1000 //hours

Number.parseInt(time[1+cookie]) * 60 * 1000 //min

Number.parseInt(time[2+cookie]) * 1000 //sec



-------------------------------------------

Insert it under the line starting with:

**const time = cell.innertext.match** 

![image_2024-07-17_151850678](https://github.com/user-attachments/assets/0fbb894a-c29a-4a9e-aa6e-4cdf5df58f39)

**Comment by nonhic** [comment]
I had made my own (far less elegant) edit to this code for the same issue, so I am grateful for this edit!  Just for posterity, I am going to clean up @Merleawe's suggestion above so it's clearer:

With regard to the original code:
https://github.com/systematic-meerca/neopets-display-scripts/blob/135c4fb16995840a779f9f04e576f194d5223687/pet-training-timer.user.js#L86-L92

replace ONLY these original lines of code [88-92]:
https://github.com/systematic-meerca/neopets-display-scripts/blob/135c4fb16995840a779f9f04e576f194d5223687/pet-training-timer.user.js#L88-L92

with the following new code (per Flutterz on Discord):
```
                let cookie = 0;
                if (cell.innerHTML.includes("strikethrough")) cookie = 3;
                totalTime = (
                    Number.parseInt(time[0+cookie]) * 60 * 60 * 1000 //hours
                    + Number.parseInt(time[1+cookie]) * 60 * 1000 //min
                    + Number.parseInt(time[2+cookie]) * 1000 //sec
                );
```
leaving a final result of:
```
            if (!complete) {
                const time = cell.innerText.match(/(\d+)/g);
                let cookie = 0;
                if (cell.innerHTML.includes("strikethrough")) cookie = 3;
                totalTime = (
                    Number.parseInt(time[0+cookie]) * 60 * 60 * 1000 //hours
                    + Number.parseInt(time[1+cookie]) * 60 * 1000 //min
                    + Number.parseInt(time[2+cookie]) * 1000 //sec
                );
            }
```

**Comment by systematic-meerca** [comment]
Thank you all! I really appreciate that so many people are both interested in these scripts and willing to help maintain em. :) Code has been updated.
